

data_path: data/dianping20.zip
over_write: False

algorithm: DC_GCN.DC_GCN
algorithm_parameters:
  n_layers: 1
  latent_dim: 64
  emb_dropout: 0
  batch_size: 2048
  lr: 0.001
  lambd: 0
  nepochs: 10000
  loss: MSE 
  resume_state: True