
data_path: data/Amazon_CDs_and_Vinyl10.zip
over_write: True

algorithm: DC_GCN.DC_GCN
algorithm_parameters:
  n_layers: 1
  latent_dim: 64
  emb_dropout: 0
  batch_size: 2048
  lr: 0.001
  lambd: 0.0001
  nepochs: 1000
  graph_noise: 0.2
  loss: MSE 
  resume_state: True