

data_path: data/douban.zip
over_write: False

algorithm: DC_GCN.DC_GCN
algorithm_parameters:
  n_layers: 5
  latent_dim: 64
  emb_dropout: 0
  batch_size: 2048
  lr: 0.0001
  lambd: 0.00001
  nepochs: 10000
  loss: MSE 
  resume_state: True